### ISSUE TITLE
Consider Rust Programming Language

### ISSUE THREAD

**Issue by za3ter2p** [UprootLabs/gngr#260]
Rust is better than Java in the resources consumption and speed, I know java is considering the security over speed but Rust got both security (memory safe) and speed more: 

Intro to the Rust programming language
https://invidio.us/watch?v=agzf6ftEsLU

The Rust Programming Language (book)
https://doc.rust-lang.org/book/

**Comment by hrj** [comment]
I have been following Rust for a long time now, even before starting the gngr project. It is a great step forward from C++ in which most other browser engines are developed.

I had mentioned Rust and Servo in [this intro](https://gngr.info/doc/introduction.html) post.

From a security point of view, Java has two benefits over Rust:
* When Java bytecode is interpreted, the Security Manager can perform sandboxing at library level. This helps us use third-party libraries without worry.
* Automatic memory management gives more legibility to code, which indirectly improves security, because code is more auditable.

While Java does have slower startup times, I think it is not a big concern for a long running process such as a browser. Moreover, these days, Java has support for AOT compilation, if you are willing to trade security for startup-speed (can't effectively sandbox libraries with AOT compiled code).

About overall speed, JVM developers are heavily investing effort in improving it. Project Valhalla is, for example, [making great strides](https://www.infoq.com/articles/inline-classes-java/).

Apart from this, we get portability and a large set of ready made libraries, including a standard GUI toolkit.

So, at this stage, Rust is not on the roadmap for this project.
